module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    colors: {
      white: '#ffffff',
      primary: '#1b98d0',
      secondary: '#61c6d8',
      tertiary: '#54cdb4',
      quaternary: '#4d7fdb',
      primary_darker: '#1989bb',
      secondary_darker: '#56b1c1',
      tertiary_darker: '#46af99',
      quaternary_darker: '#426ebf',
      body: '#c1c1c1',
      alternate: '#999999',
      muted: '#727272',
      separator: '#474747',
      separator_light: '#2e2e2e',
      background: '#1d1d1d',
      foreground: '#242424',
      background_theme: '#242424',
      background_light: '#292929',
      gradient_1: ' #1b98d0',
      gradient_2: '#1d9dd7',
      gradient_3: '#1ea5e1',
      gradient_1_lighter: '#1ea5e1',
      gradient_1_darker: '#1a90c5',
      light_text: ' #f0f0f0',
      dark_text: '#191c1f',
      light_text_darker: '#e9e9e9',
      dark_text_darker: '#08090a',
      danger: '#b62836',
      info: '#298a99',
      warning: ' #ebb71a',
      success: '#418b38',
      light: '#dadada',
      dark: '#4e4e4e',
      danger_darker: ' #771a23',
      info_darker: '#19545d',
      warning_darker: '#aa830f',
      success_darker: '#285422',
      light_darker: ' #c9c9c9',
      dark_darker: '#282828',
      body_darker: ' #a0a0a0',
      alternate_darker: ' #6e6e6e',
      muted_darker: ' #4e4e4e',
      separator_darker: '#353535',
    },
    borderRadius: {
      none: '0',
      sm: '0.25rem',
      md: '0.5rem',
      lg: '1rem',
      xl: '1.5rem',
    },
    fontFamily: {
      montserratMedium: ['Montserrat Medium', 'sans-serif'],
      montserratBold: ['Montserrat Bold', 'sans-serif'],
      montserratExtraBold: ['Montserrat ExtraBold', 'sans-serif'],
      sourceSansPro: ['Source Sans Pro Regular', 'sans-serif'],
    },
    extend: {},
  },
  plugins: [],
};
